{
 "title": "lhm_exporter",
 "tags": [
  "lhm_exporter",
  "LibreHardwareMonitor",
  "windows_exporter",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(lhm_cpu_clock_mhz,instance)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(lhm_gpu_data_bytes{instance=~\"$instance\"},parent_name)"
    }
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "label_values(lhm_cpu_clock_mhz{instance=~\"$instance\"},parent_name)"
    }
   },
   {
    "name": "motherboard",
    "label": "Motherboard Chipset",
    "query": {
     "query": "label_values(lhm_motherboard_control_percent{instance=~\"$instance\"},parent_name)"
    }
   },
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(lhm_network_data_bytes{instance=~\"$instance\"},parent_name)"
    }
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": {
     "query": "label_values(lhm_disk_data_bytes{instance=~\"$instance\"},parent_identifier)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instance",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><center>$instance</center></h1>"
   }
  },
  {
   "title": "CPU - $cpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "cpu",
   "collapsed": true,
   "panels": [
    { "title": "Model", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 }, "options": { "content": "# $cpu" } },
    {
     "title": "Cpu Clock",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "lhm_cpu_clock_mhz{instance=~\"$instance\",parent_name=~\"$cpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "lhm_cpu_voltage_volts{instance=~\"$instance\",parent_name=~\"$cpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Cpu Load",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "lhm_cpu_load_percent{instance=~\"$instance\",parent_name=~\"$cpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Power Consumption",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "lhm_cpu_power_watts{instance=~\"$instance\",parent_name=~\"$cpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "lhm_cpu_temperature_celsius{instance=~\"$instance\",parent_name=~\"$cpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "lhm_cpu_current_amperes{instance=~\"$instance\",parent_name=~\"$cpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Cpu Factor",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "lhm_cpu_factor_total{instance=~\"$instance\",parent_name=~\"$cpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - $gpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "gpu",
   "collapsed": true,
   "panels": [
    { "title": "Model", "type": "text", "gridPos": { "h": 3, "w": 13, "x": 0, "y": 5 }, "options": { "content": "# $gpu" } },
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "lhm_gpu_data_bytes{instance=~\"$instance\",parent_name=~\"$gpu\",name=\"GPU Memory Used\"}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "lhm_gpu_data_bytes{instance=~\"$instance\",parent_name=~\"$gpu\",name=\"GPU Memory Total\"}",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "GPU Clock",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "lhm_gpu_clock_mhz{instance=~\"$instance\",parent_name=~\"$gpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "GPU Factor",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "lhm_gpu_factor_total{instance=~\"$instance\",parent_name=~\"$gpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Fan Control",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 9, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "lhm_gpu_control_percent{instance=~\"$instance\",parent_name=~\"$gpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "GPU Load",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "lhm_gpu_load_percent{instance=~\"$instance\",parent_name=~\"$gpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Power Consumption",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "lhm_gpu_power_watts{instance=~\"$instance\",parent_name=~\"$gpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "lhm_gpu_temperature_celsius{instance=~\"$instance\",parent_name=~\"$gpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "lhm_gpu_power_watts{instance=~\"$instance\",parent_name=~\"$gpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Fan RPM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "expr": "lhm_gpu_fan_rpm{instance=~\"$instance\",parent_name=~\"$gpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "lhm_gpu_throughput_bytes_per_seconds{instance=~\"$instance\",parent_name=~\"$gpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Motherboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Motherboard Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1889 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "lhm_motherboard_temperature_celsius{instance=~\"$instance\",parent_name=~\"$motherboard\"}",
       "legendFormat": "[{{parent_name}}] {{name}}"
      }
     ]
    },
    {
     "title": "Motherboard Control",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1889 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "lhm_motherboard_control_percent{instance=~\"$instance\",parent_name=~\"$motherboard\"}",
       "legendFormat": "[{{parent_name}}] {{name}}"
      }
     ]
    },
    {
     "title": "Motherboard Fan Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1897 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "expr": "lhm_motherboard_fan_rpm{instance=~\"$instance\",parent_name=~\"$motherboard\"}",
       "legendFormat": "[{{parent_name}}] {{name}}"
      }
     ]
    },
    {
     "title": "Motherboard Voltage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1897 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "lhm_motherboard_voltage_volts{instance=~\"$instance\",parent_name=~\"$motherboard\"}",
       "legendFormat": "[{{parent_name}}] {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Generic Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5723 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "lhm_memory_data_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Generic Memory Load",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5723 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "lhm_memory_load_percent{instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Data",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 330 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "lhm_network_data_bytes{instance=~\"$instance\",parent_name=~\"$network\"}",
       "legendFormat": "[{{parent_name}}] {{name}}"
      }
     ]
    },
    {
     "title": "Network Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 363 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "lhm_network_throughput_bytes_per_seconds{instance=~\"$instance\",parent_name=~\"$network\"}",
       "legendFormat": "[{{parent_name}}] {{name}}"
      }
     ]
    },
    {
     "title": "Network Load",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 372 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "lhm_network_load_percent{instance=~\"$instance\",parent_name=~\"$network\"}",
       "legendFormat": "[{{parent_name}}] {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 331 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "lhm_disk_data_bytes{instance=~\"$instance\",parent_identifier=~\"$disk\"}",
       "legendFormat": "[{{parent_name}} ({{parent_identifier}})] {{name}}"
      }
     ]
    },
    {
     "title": "Disk Factor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 331 },
     "targets": [
      {
       "expr": "lhm_disk_factor_total{instance=~\"$instance\",parent_identifier=~\"$disk\"}",
       "legendFormat": "[{{parent_name}} ({{parent_identifier}})] {{name}}"
      }
     ]
    },
    {
     "title": "Disk Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 339 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "lhm_disk_temperature_celsius{instance=~\"$instance\",parent_identifier=~\"$disk\"}",
       "legendFormat": "[{{parent_name}} ({{parent_identifier}})] {{name}}"
      }
     ]
    },
    {
     "title": "Disk Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 339 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "lhm_disk_level_percent{instance=~\"$instance\",parent_identifier=~\"$disk\"}",
       "legendFormat": "[{{parent_name}} ({{parent_identifier}})] {{name}}"
      }
     ]
    },
    {
     "title": "Disk Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 347 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "lhm_disk_throughput_bytes_per_seconds{instance=~\"$instance\",parent_identifier=~\"$disk\"}",
       "legendFormat": "[{{parent_name}} ({{parent_identifier}})] {{name}}"
      }
     ]
    },
    {
     "title": "Disk Load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 347 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "lhm_disk_load_percent{instance=~\"$instance\",parent_identifier=~\"$disk\"}",
       "legendFormat": "[{{parent_name}} ({{parent_identifier}})] {{name}}"
      }
     ]
    }
   ]
  }
 ]
}